# Generated by Django 5.2 on 2025-06-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_web', '0006_alter_contact_date_alter_contact_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateField(default='13:06:2025'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='time',
            field=models.TimeField(default='16:05:26'),
        ),
    ]
