# Generated by Django 5.2 on 2025-07-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_web', '0011_alter_contact_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='time',
            field=models.TimeField(default='15:19:21'),
        ),
    ]
