# Generated by Django 5.2 on 2025-07-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_web', '0014_alter_contact_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateField(default='08:07:2025'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='time',
            field=models.TimeField(default='16:17:40'),
        ),
    ]
