# Generated by Django 5.2 on 2025-06-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_userdata_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
