# Generated by Django 5.2 on 2025-07-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_userdata_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Tejas')),
                ('last_name', models.CharField(default='Varute')),
            ],
        ),
    ]
