# Generated by Django 5.2 on 2025-07-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_developer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='first_name',
            field=models.CharField(default='Tejas', max_length=10),
        ),
        migrations.AlterField(
            model_name='developer',
            name='last_name',
            field=models.CharField(default='Varute', max_length=10),
        ),
    ]
